### ISSUE TITLE
Fixes in anonymized views at different places

### ISSUE THREAD

**Issue by pranavgaikwad** [shubham-pampattiwar/expertiza#6]
In some places, anonymized names are not shown. For example, heatgrid view. We need to fix occurrences in different parts of the application where anonymized names are not shown.

Some identified views : 
- HeatGrid View : On 'view grades' page, there are different tabs where detailed scores, reviews, etc are displayed in a table. The table's column title use real names of the students even when Anonymized mode is set.
- Grade Reports : Similarly, on grades page, we can see overall reports of student grades. When in Anonymized mode, the student names are not anonymized in reports.

**Comment by pranavgaikwad** [comment]
@deepayanbardhan would like your help on this one

**Comment by deepayanbardhan** [comment]
Ok, I'm looking into it.

**Comment by pranavgaikwad** [comment]
@deepayanbardhan View Heatgrid looks like a non-issue. please confirm. Same is true for grade reports

**Comment by deepayanbardhan** [comment]
@pranavgaikwad View Heatgrid does not look like an issue to me so is the grade report. It is working as it is supposed to.

**Comment by pranavgaikwad** [comment]
@deepayanbardhan thanks for the update. we will raise this upstream
